services:
  - docker

script:
  - docker run -v ${PWD}:/segger/firefly alexeyeremin/nrf-sdk-15-3-segger /segger/ses/bin/emBuild firefly/nrf52/blank/ses/firefly.emProject -config 'Debug' -D 'NRF_SDK_PATH=/segger/nRF5_SDK_15.3.0'
  - docker run -v ${PWD}:/segger/firefly alexeyeremin/nrf-sdk-15-3-segger /segger/ses/bin/emBuild firefly/nrf52/blank/ses/firefly.emProject -config 'Release' -D 'NRF_SDK_PATH=/segger/nRF5_SDK_15.3.0'

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: nrf52/blank/ses/Output/Debug/Exe/demo.hex
  skip_cleanup: true
  on:
    tags: true