services:
  - docker

script:
  - docker run -v ${PWD}:/segger/firefly alexeyeremin/nrf-sdk-15-3-segger /segger/ses/bin/emBuild firefly/nrf52/blank/ses/firefly.emProject -config 'Debug' -D 'NRF_SDK_PATH=/segger/nRF5_SDK_15.3.0'